In [1]:
#zadania pisemne wysłać przez pdf
#funkcja odwracania
#funckja mnożenia macierzy
#funkcja wyznacznika macierzy

In [2]:
import numpy as np

In [3]:
def det(A):
    n,m = A.shape
    if n != m:
        raise ValueError("Podana macierz nie jest kwadratowa")
    if n == 1:
        return A[0,0]
    if n == 2:
        return A[0,0]*A[1,1] - A[0,1]*A[1,0]
    sum = 0
    for j in range(m):
        sum += np.power(-1,1+(j+1))*A[0,j]*det(np.delete(np.delete(A,0,0),j,1))
    return sum

def matmul(A,B):
    n,m = A.shape
    k,l = B.shape

    if m!=k:
        raise ValueError("Macierze mają nieodpowiednie wymiary")
    AB = np.zeros((n,l))
    for i in range(n):
        for j in range(l):
            AB[i,j] = np.sum([A[i,o]*B[p,j] for o,p in zip(range(m),range(k))])
    return AB

def transpose(A):
    n,m = A.shape
    B = np.zeros((m,n))
    for j in range(m):
        for i in range(n):
            B[j,i] = A[i,j]
    return B

def dopelnienie(A):
    n, m = A.shape
    D = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
            D[i][j] = np.power(-1,(i+1)+(j+1))*det(np.delete(np.delete(A,i,0),j,1))
    return D

def matrix_inv(A):
    det_A = det(A)
    if det_A == 0:
        raise ValueError("Nie można odwrócić macierzy: macierz osobliwa")
    D = dopelnienie(A)
    D_T = np.matrix.transpose(D)
    return 1/(det_A) * D_T

def lu_decomp_pivot(A):
    # Rozmiar macierzy
    A = np.float64(A)
    n = A.shape[0]
    
    # Inicjalizacja
    P = np.eye(n)
    L = np.zeros((n, n))
    U = A.copy()
    
    for i in range(n):
        # Znajdź indeks największego elementu
        pivot_index = np.argmax(abs(U[i:, i])) + i
        
        # Zamiana wierszy w U i P
        if pivot_index != i:
            U[[i, pivot_index]] = U[[pivot_index, i]]
            P[[i, pivot_index]] = P[[pivot_index, i]]
            L[[i, pivot_index]] = L[[pivot_index, i]]

        # Obliczanie elementów macierzy L i U
        for j in range(i + 1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j, i:] -= L[j, i] * U[i, i:]


        # Ustawienie jedynek na przekątnej macierzy L
    np.fill_diagonal(L, 1)

    
    return P, L, U

W zadaniach, w których należy rozwiązać układ równań A*x = b będziemy korzystać z metody odwrócenia macierzy A. Jeśli macierz A jest nieodwracalna, wtedy skorzystamy z metody dekompozycji LU z macierzą pivotową P

# Zadanie 4

Rozwiązać układ równań Ax= b

In [4]:
A = np.matrix([
    [0,0,2,1,2],
    [0,1,0,2,-1],
    [1,2,0,-2,0],
    [0,0,0,-1,1],
    [0,1,-1,1,-1]])
b = np.matrix([
     [1],
     [1],
     [-4],
     [-2],
     [-1]])

A_inv = matrix_inv(A)
x = matmul(A_inv,b)
print("Rozwiązanie: x = ")
print(x)# rozwiązanie
print("Sprawdzenie: A*x = ")
print(matmul(A,x))



Rozwiązanie: x = 
[[ 2.]
 [-2.]
 [ 1.]
 [ 1.]
 [-1.]]
Sprawdzenie: A*x = 
[[ 1.]
 [ 1.]
 [-4.]
 [-2.]
 [-1.]]


# Zadanie 5

In [5]:
points = [(0,-1),(1,1),(3,3),(5,2),(6,-2)]
n = len(points)
A = np.zeros((n,n))
for i in range(n):
    x = points[i][0]
    A[i][0] = 1
    A[i][1] = x
    A[i][2] = x**2
    A[i][3] = x**3
    A[i][4] = x**4
b = [[-1],[1],[3],[2],[-2]]

A_inv = matrix_inv(A)

result = np.matmul(A_inv,b)
result=np.round(result,3)

print("a_0 = {}, a_1 = {}, a_2 = {}, a_3 = {}, a_4 = {}".format(result[0][0],result[1][0],result[2][0],result[3][0],result[4][0]))


a_0 = -1.0, a_1 = 2.683, a_2 = -0.875, a_3 = 0.217, a_4 = -0.025


# Zadanie 6

In [6]:
A = np.matrix([
    [3.50, 2.77, -0.76, 1.80],
    [-1.80, 2.68, 3.44, -0.09],
    [0.27, 5.07, 6.9, 1.61],
    [1.71, 5.45, 2.68, 1.71]
])
b = np.matrix([[7.31], [4.23], [13.85], [11.55]])

A_inv = matrix_inv(A)

x = np.matmul(A_inv,b)

print("Rozwiązanie:")
print(x) 
print("Det(A)={}".format(det(A)))
print("Sprawdzenie rozwiązania, A*x:")
print(matmul(A,x))


Rozwiązanie:
[[1.]
 [1.]
 [1.]
 [1.]]
Det(A)=-0.22579733999999974
Sprawdzenie rozwiązania, A*x:
[[ 7.31]
 [ 4.23]
 [13.85]
 [11.55]]


Wyznacznik macierzy nie jest dużo mniejszy niż najmniejsza wartość macierzy A, zatem jest dobrze uwarunkowana. Po sprawdzeniu rozwiązania, czyli wykonaniu mnożenia A*x otrzymaliśmy b, zatem rozwiązanie jest dokładne.

# Zadanie 7

In [7]:
A = np.matrix([
    [10, -2, -1, 2, 3, 1, -4, 7],
    [5, 11, 3, 10, -3, 3, 3, -4],
    [7, 12, 1, 5, 3, -12, 2, 3],
    [8, 7, -2, 1, 3, 2, 2, 4],
    [2, -15, -1, 1, 4, -1, 8, 3],
    [4, 2, 9, 1, 12, -1, 4, 1],
    [-1, 4, -7, -1, 1, 1, -1, -3],
    [-1, 3, 4, 1, 3, -4, 7, 6]
])
b = np.matrix([[0],[12],[-5],[3],[-25],[-26],[9],[-7]])

A_inv = matrix_inv(A)
x = matmul(A_inv,b)

In [8]:
print("Rozwiązanie: x = ")
print(x)
print("Sprawdzenie: A*x = ")
print(matmul(A,x))


Rozwiązanie: x = 
[[-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]]
Sprawdzenie: A*x = 
[[  0.]
 [ 12.]
 [ -5.]
 [  3.]
 [-25.]
 [-26.]
 [  9.]
 [ -7.]]


# Zadanie 8

In [9]:
A = np.matrix([
    [2, -1, 0, 0, 0, 0],
    [-1, 2, -1, 0, 0, 0],
    [0, -1, 2, -1, 0, 0],
    [0, 0, -1, 2, -1, 0],
    [0, 0, 0, -1, 2, -1],
    [0, 0, 0, 0, -1, 5]
])

print(matrix_inv(A))



[[0.84 0.68 0.52 0.36 0.2  0.04]
 [0.68 1.36 1.04 0.72 0.4  0.08]
 [0.52 1.04 1.56 1.08 0.6  0.12]
 [0.36 0.72 1.08 1.44 0.8  0.16]
 [0.2  0.4  0.6  0.8  1.   0.2 ]
 [0.04 0.08 0.12 0.16 0.2  0.24]]


Macierz odwrotna nie jest trójdiagonalna. 

# Zadanie 9

In [10]:
A = np.matrix([
    [1, 3, -9, 6, 4],
    [2, -1, 6, 7, 1],
    [3, 2, -3, 15, 5],
    [8, -1, 1, 4, 2],
    [11, 1, -2, 18, 7]
])
A_inv = matrix_inv(A) 
print(A_inv)

ValueError: Nie można odwrócić macierzy: macierz osobliwa

Nie można odwrócić tej macierzy, gdyż jest ona nieosobliwa

In [ ]:
A_inv = np.linalg.inv(A)
np.matmul(A,A_inv)

matrix([[ 2. ,  0. ,  2. , -4. ,  4. ],
        [-0.5,  1.5, -0.5, -1. ,  1. ],
        [-1. ,  0. ,  4. , -2. ,  2. ],
        [ 0. ,  0. , -1. ,  0. ,  0. ],
        [ 1. ,  0. ,  0. , -6. ,  6. ]])

Metody z biblioteki numpy też sobie z tym nie poradziły, gdyż końcowo z mnożenia $A* A^{-1}$ nie wyszła nam macierz jednostkowa